### ISSUE TITLE
privatePerson's required nationality property

### ISSUE THREAD

**Issue by salatti** [FinnishCustoms-SuomenTulli/account-register-information-update#22]
Hi,

Related to the latest schema update, should the required property of "nationality" be changed to correspond the new "nationalities" property?

https://github.com/FinnishCustoms-SuomenTulli/account-register-information-update/blob/f15a7e7901efde3297231cdc3ab8400f075571d2/schemas/information_update.json#L214

BR, Altti

**Comment by ext-attelaine** [comment]
Hi,
Yes it should, good point. Thank you.
(edit. pr: #23)
Atte

**Comment by ext-alexpeltonen** [comment]
Merged #23
